extends:
  - "@redhat-cloud-services/eslint-config-redhat-cloud-services"
  - "plugin:cypress/recommended"
root: true
globals:
  insights: 'readonly'
  shallow: readonly
  render: 'readonly'
  mount: 'readonly'
rules:
  rulesdir/forbid-pf-relative-imports: off
